name: dose_crop_calc
description: 放疗计划裁剪距离计算器
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

workflows:
  flutter-build:
    name: Build Flutter App
    environment:
      flutter: stable
      xcode: latest
      cocoapods: 1.15.0
    scripts:
      # ✅ 关键：进入 Flutter 项目目录
      - cd lib        # 替换为你的实际项目文件夹名
      - flutter pub get
      - flutter build apk --release
      - flutter build ios --release --no-codesign
    artifacts:
      - flutterApp/build/app/outputs/apk/release/app-release.apk
      - flutterApp/build/ios/ipa/*.ipa
